import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function runMigration() {
  console.log('Starting DB Migration...');

  try {
    // 1. Drop existing FK constraint on User if present
    await prisma.$executeRawUnsafe(`ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_department_id_fkey";`);

    // 2. Rename old department_id in Department to old_department_id if not already done
    const cols: any[] = await prisma.$queryRawUnsafe(`
      SELECT column_name FROM information_schema.columns 
      WHERE table_name = 'Department';
    `);
    const colNames = cols.map(c => c.column_name);
    console.log('Current Department columns:', colNames);

    if (colNames.includes('department_id') && !colNames.includes('old_department_id')) {
      // Check data type of department_id
      const dataType: any[] = await prisma.$queryRawUnsafe(`
        SELECT data_type FROM information_schema.columns 
        WHERE table_name = 'Department' AND column_name = 'department_id';
      `);
      if (dataType[0]?.data_type === 'text' || dataType[0]?.data_type === 'character varying') {
        await prisma.$executeRawUnsafe(`ALTER TABLE "Department" DROP CONSTRAINT IF EXISTS "Department_pkey";`);
        await prisma.$executeRawUnsafe(`ALTER TABLE "Department" RENAME COLUMN "department_id" TO "old_department_id";`);
      }
    }

    // Refresh columns
    const cols2: any[] = await prisma.$queryRawUnsafe(`
      SELECT column_name FROM information_schema.columns WHERE table_name = 'Department';
    `);
    const colNames2 = cols2.map(c => c.column_name);

    if (!colNames2.includes('department_id')) {
      console.log('Adding new INTEGER department_id with identity auto-increment...');
      await prisma.$executeRawUnsafe(`ALTER TABLE "Department" ADD COLUMN "department_id" INT GENERATED BY DEFAULT AS IDENTITY;`);
    }

    // Ensure Department_pkey exists on department_id
    console.log('Setting Primary Key on Department(department_id)...');
    await prisma.$executeRawUnsafe(`ALTER TABLE "Department" DROP CONSTRAINT IF EXISTS "Department_pkey";`);
    await prisma.$executeRawUnsafe(`ALTER TABLE "Department" ADD CONSTRAINT "Department_pkey" PRIMARY KEY ("department_id");`);

    // Ensure department_name is VARCHAR(100) NOT NULL UNIQUE
    console.log('Configuring department_name column...');
    await prisma.$executeRawUnsafe(`ALTER TABLE "Department" ALTER COLUMN "department_name" TYPE VARCHAR(100);`);
    await prisma.$executeRawUnsafe(`ALTER TABLE "Department" ALTER COLUMN "department_name" SET NOT NULL;`);
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "Department" ADD CONSTRAINT "Department_department_name_key" UNIQUE ("department_name");`);
    } catch (e) {
      // already exists
    }

    // Now update User table
    console.log('Updating User table department_id...');
    const userCols: any[] = await prisma.$queryRawUnsafe(`
      SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'User';
    `);
    const userDeptCol = userCols.find(c => c.column_name === 'department_id');

    if (userDeptCol && (userDeptCol.data_type === 'text' || userDeptCol.data_type === 'character varying')) {
      await prisma.$executeRawUnsafe(`ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "new_department_id" INTEGER;`);

      if (colNames2.includes('old_department_id')) {
        await prisma.$executeRawUnsafe(`
          UPDATE "User" u
          SET "new_department_id" = d."department_id"
          FROM "Department" d
          WHERE u."department_id" = d."old_department_id" OR u."department_id" = d."department_name";
        `);
      } else {
        await prisma.$executeRawUnsafe(`
          UPDATE "User" u
          SET "new_department_id" = d."department_id"
          FROM "Department" d
          WHERE u."department_id"::text = d."department_id"::text OR u."department_id" = d."department_name";
        `);
      }

      await prisma.$executeRawUnsafe(`
        UPDATE "User"
        SET "new_department_id" = (SELECT "department_id" FROM "Department" LIMIT 1)
        WHERE "new_department_id" IS NULL;
      `);

      await prisma.$executeRawUnsafe(`ALTER TABLE "User" DROP COLUMN "department_id";`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "User" RENAME COLUMN "new_department_id" TO "department_id";`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "User" ALTER COLUMN "department_id" SET NOT NULL;`);
    }

    // Drop old_department_id from Department if present
    if (colNames2.includes('old_department_id')) {
      await prisma.$executeRawUnsafe(`ALTER TABLE "Department" DROP COLUMN "old_department_id";`);
    }

    // Restore FK constraint from User.department_id to Department.department_id
    console.log('Restoring Foreign Key constraint...');
    await prisma.$executeRawUnsafe(`
      ALTER TABLE "User" ADD CONSTRAINT "User_department_id_fkey" 
      FOREIGN KEY ("department_id") REFERENCES "Department"("department_id") 
      ON DELETE RESTRICT ON UPDATE CASCADE;
    `);

    // Handle PendingRegistration table if present
    const pendingCols: any[] = await prisma.$queryRawUnsafe(`
      SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'PendingRegistration';
    `);
    const pendingDeptCol = pendingCols.find(c => c.column_name === 'department_id');

    if (pendingDeptCol && (pendingDeptCol.data_type === 'text' || pendingDeptCol.data_type === 'character varying')) {
      await prisma.$executeRawUnsafe(`ALTER TABLE "PendingRegistration" ADD COLUMN IF NOT EXISTS "new_department_id" INTEGER;`);
      await prisma.$executeRawUnsafe(`
        UPDATE "PendingRegistration" p
        SET "new_department_id" = d."department_id"
        FROM "Department" d
        WHERE p."department_id" = d."department_name";
      `);
      await prisma.$executeRawUnsafe(`
        UPDATE "PendingRegistration"
        SET "new_department_id" = (SELECT "department_id" FROM "Department" LIMIT 1)
        WHERE "new_department_id" IS NULL;
      `);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PendingRegistration" DROP COLUMN "department_id";`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PendingRegistration" RENAME COLUMN "new_department_id" TO "department_id";`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PendingRegistration" ALTER COLUMN "department_id" SET NOT NULL;`);
    }

    console.log('MIGRATION COMPLETED SUCCESSFULLY!');
  } catch (err) {
    console.error('Migration error:', err);
  }
}

runMigration()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
