export const ENGINEERING_DOMAINS: string[] = [
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Electronics & Communication Engineering",
  "Computer Science & Engineering",
  "Information Technology",
  "Artificial Intelligence",
  "Machine Learning",
  "Artificial Intelligence & Machine Learning",
  "Data Science & Analytics",
  "Big Data Analytics",
  "Cyber Security",
  "Information Security",
  "Internet of Things (IoT)",
  "Industrial IoT",
  "Blockchain & Web3",
  "Cloud Computing",
  "Edge Computing",
  "DevOps",
  "Software Engineering",
  "Software Testing & Quality Assurance",
  "Web Development",
  "Mobile Application Development",
  "Database Management",
  "Computer Networks",
  "Distributed Systems",
  "Embedded Systems",
  "VLSI & Chip Design",
  "Semiconductor Technology",
  "Computer Vision",
  "Image Processing",
  "Natural Language Processing",
  "Computer Graphics",
  "Robotics",
  "Robotics & Automation",
  "Intelligent Automation",
  "Autonomous Systems",
  "Mechatronics Engineering",
  "Automobile Engineering",
  "Automotive & Mobility",
  "Aeronautical Engineering",
  "Aerospace Engineering",
  "Space Technology",
  "Aerospace & Defence",
  "Defence Technology",
  "Chemical Engineering",
  "Chemical & Process Engineering",
  "Biotechnology",
  "Biomedical Engineering",
  "Healthcare & Medical",
  "Healthcare Informatics",
  "HealthTech",
  "Pharmaceuticals",
  "Industrial Engineering",
  "Production Engineering",
  "Manufacturing Engineering",
  "Smart Manufacturing",
  "Manufacturing & Industry",
  "Metallurgical & Materials Engineering",
  "Mining & Minerals",
  "Mining Engineering",
  "Petroleum Engineering",
  "Oil & Gas",
  "Marine Engineering",
  "Marine & Ocean",
  "Agricultural Engineering",
  "Agriculture & Farming",
  "Smart Agriculture",
  "AgriTech",
  "Food Technology",
  "Food & Agriculture",
  "Textile Engineering",
  "Textile & Fashion Technology",
  "Polymer Engineering",
  "Environmental Engineering",
  "Environment & Sustainability",
  "Climate Change & Sustainability",
  "Energy Engineering",
  "Renewable Energy",
  "Renewable Energy Engineering",
  "Energy & Power Systems",
  "Energy Management",
  "Nanotechnology",
  "Quantum Computing",
  "Quantum Machine Learning",
  "AR/VR & Metaverse",
  "Game Development",
  "Gaming & Game Technology",
  "UI/UX Design",
  "Human-Computer Interaction",
  "Digital Twin & Simulation",
  "Digital Transformation",
  "Business Intelligence",
  "Business Analytics",
  "Business & Management",
  "FinTech",
  "Banking & Finance",
  "Financial Technology",
  "E-Commerce Technology",
  "E-Commerce & Retail",
  "EdTech",
  "Education & E-Learning",
  "GovTech & Public Services",
  "E-Governance",
  "LegalTech",
  "Social Welfare & Community Development",
  "Social Innovation",
  "Rural Development",
  "Rural Technology",
  "Urban Development",
  "Smart City",
  "Smart Infrastructure",
  "Construction Engineering",
  "Construction & Infrastructure",
  "Structural Engineering",
  "Transportation Engineering",
  "Smart Transportation",
  "Transportation & Logistics",
  "Supply Chain & Logistics",
  "Water Resources Engineering",
  "Water Management",
  "Waste Management",
  "Disaster Management",
  "Disaster Prediction & Management",
  "Public Safety & Security",
  "Smart Home & Automation",
  "Assistive Technology",
  "Accessibility & Inclusive Technology",
  "Media & Entertainment",
  "Tourism & Hospitality",
  "Communication & Networking",
  "Privacy & Data Protection",
  "Enterprise Application Development",
  "Software & Applications",
  "Digital Health",
  "Smart Healthcare",
  "Smart Energy",
  "Smart Mobility",
  "Smart Environment",
  "Green Technology",
  "Sustainable Technology",
  "FinTech & Digital Banking",
  "AgriTech & Smart Farming",
  "EdTech & Digital Learning",
  "HealthTech & Medical Technology",
  "IoT & Smart Systems",
  "AI-Powered Systems",
  "Cybersecurity & Privacy",
  "Automation & Control Systems",
  "Emerging Technologies"
];
